src/assets/javascripts/helpers/reddit.js

The instance `https://libreddit.himiko.cloud` redirects to some random malicious sites which are usually blocked by ublock.

Remove libreddit.himiko.cloud instance

---

README.md

Users who want to build LibRedirect as a WebExtension must install [web-ext](https://www.npmjs.com/package/web-ext) or they will face an error.

Add web-ext dependency

---

src/assets/javascripts/helpers/youtube/youtube.js

Added Piped Instances of the below following :
- https://piped.syncpundit.com
- https://piped.privacy.com.de
Unable to add the below instances because of inability to access them.
- https://piped.moomoo.me
- https://piped.notyourcomputer.net
The above are not added because you cannot access them via the Frontend but only by the API.

Added New Piped Instances

---

src/pages/options/search/search.html

Hello. This fixes a typo on the Search page.
it's full potential -> its full potential

Fixes typo on the Search page

---

src/assets/javascripts/helpers/instagram.js

It fixes IGTV URLs (ex. https://www.instagram.com/tv/CamQ9IytDGO/) redirecting to something like https://bibliogram.art/p/tv/CamQ9IytDGO/

Fix replace command for IGTV path

---

src/assets/javascripts/youtube/youtube.js

Otherwise FreeTube will open but fail to load the video.

fix: missing slash in freetube redirect url

---

src/assets/javascripts/youtubeMusic.js

https://music.youtube.com/search?q=test 
now redirects to
https://beatbump.ml/search/test?filter=EgWKAQIIAWoKEAMQBBAKEAkQBQ%3D%3D 
instead of going to the 404 page of beatbump.
I don't know why beatbump has such a weird url scheme for the search.
Thanks for the great extension!

Add redirect of youtubeMusic search query to beatbump

---

src/instances/get_instances.py

Resolves #460. `src/instances/get_instances.py` will process the list of instances at [`instances.json` in libbacon/libreddit-instances](https://github.com/libbacon/libreddit-instances/blob/c215cd64ea9e4de88c59af0e24d355509d4182ca/instances.json).
Tested and confirmed working.

(#460) get Libreddit instances from libbacon/libreddit-instances

---

src/instances/get_instances.py

The libbacon project org has changed its name to [ferritreader](https://github.com/ferritreader). This PR makes the appropriate change to src/instances/get_instances.py to fetch the libreddit instances JSON from the libreddit-instances repo in the ferritreader project.

Update fetch url for Libreddit instances.

---

src/instances/get_instances.py

With the resumption of the Libreddit project, the repo containing the instances that I started in [ferritreader](https://github.com/ferritreader) has moved to [libreddit/libreddit-instances](https://github.com/libreddit/libreddit-instances). This commit fixes the URL for libreddit instances to point to that repo.

Fix link to libreddit-instances JSON.

---

src/config/config.json
src/instances/get_instances.py

[Ferrit has been discontinued with the resumption of the Reddit project.](https://github.com/ferritreader/ferrit/discussions/61) This PR removes all references to Ferrit in `src/config/config.json` and amends `src/instances/get_instances.py` not to pull the list of Ferrit instances anymore. (The instances repo has been deleted.)

Remove Ferrit.

---

src/instances/get_instances.py

The official instance list was moved to a JSON file, as found on https://docs.breezewiki.com/Links.html#%28part._.Instances%29

Fix instance fetching for BreezeWiki

---

src/assets/javascripts/services.js

Currently, if an answer is linked in the url, the url expands to 2 ids, the first one being the thread, and the second being the answer. Anonymous Overflow at the moment, doesn't support linking to answers, you'll just get a `404 page not found`, `url.hash`ing doesn't work either (or rather, it doesn't 404, but it doesn't actually link you to the answer), this PR fixes this by grabbing the thread ID directly.
example:
https://stackoverflow.com/a/11227902
https://stackoverflow.com/questions/11227809/why-is-processing-a-sorted-array-faster-than-processing-an-unsorted-array/11227902

services: Fix `anonymousOverflow` redirect when answers are linked

---

src/assets/javascripts/services.js

You can link to sub-sections of a Wikipedia article using URL hash, such as in `https://en.wikipedia.org/wiki/Survivorship_bias#Military`. This also works on wikiless. This PR adds requested hash to redirected URLs.

Preserve URL hash on wikiless redirection

---

src/assets/javascripts/services.js

YouTube live chat on live streams and replays uses an iframe to display the chat alongside the video, so Libredirect will try to redirect it when it is set to only redirect YouTube embeds. All YouTube services will 404 when trying to redirect the chat. This PR adds an exception for live chat pages when redirecting Invidious, Piped (Material), CloudTube, and PokeTube.

Fix YouTube livestream chat breaking on embed only mode

---

src/pages/popup/popup.js
src/pages/popup/popup.pug
src/pages/widgets/switches.pug

Currently all buttons are created visible and the script asynchronously hides them; this causes the popup menu to display all buttons for a split second when opened, which is very annoying and distracting. This PR makes buttons visible only if they are needed.
Duplicated code was removed, which should also improve performance.

Refactor popup menu

---

src/config.json

The Librarian pussied out lol: https://bcow.xyz/posts/archiving-librarian/
Suds been down for quite some time, might remove it for the time being and then re-add it if he's going to come back.
Source code: https://git.vern.cc/cobra/Suds
Wayback Machine: https://web.archive.org/web/20230314215806if_/https://git.vern.cc/cobra/suds

Snopes Frontend & Librarian Frontend Are Down

---

src/config.json

- removed useless `|` in groups (`(if1|if2|)` -> `(if1|if2)`)
- make `www` optional everywhere I could (fixed twitter, cuz it's not redirects to www)
- Make some groups non-capturing

WWW regex improve

---

src/assets/javascripts/services.js

youtu.be urls are only used for videos so FreeTube was having issues when receiving non video links (as FreeTube assumes that youtu.be is a video)
fixes https://github.com/FreeTubeApp/FreeTube/issues/3846

Fix FreeTube for non-video urls

---

src/assets/javascripts/services.js
src/config.json

Example URLs:
```
https://staff.tumblr.com/ ----> https://pb.bloat.cat/staff/
https://staff.tumblr.com/post/736071326097440768/hello-tumblr-this-is-a-badges-update ----> https://pb.bloat.cat/staff/736071326097440768/hello-tumblr-this-is-a-badges-update
https://www.staff.tumblr.com ----> https://pb.bloat.cat/staff
```

Add redirects from Tumblr blogs to Priviblur

---

src/assets/javascripts/services.js

Problem:
When I browse YouTube on Invidious, I frequently jump back to youtube.com without disabling the extension by clicking "Watch on YouTube" on Invidious page. After that, when I click some link in the description section (it comes in this format usually https://www.youtube.com/redirect?event=.....), the extension cannot handle it correctly and it returns the homepage of Invidious instance instead.

Disable redirection when a link in the YouTube description section is entered

---

.gitignore
src/assets/javascripts/services.js
src/config.json

- Stack Overflow regex changed to support other languages like es.stackoverflow.com or ru.stackoverflow.com
- "Home" urls (like `https://tor.stackexchange.com/`) now redirects to home randomInstance
- Support other Stack Exchange sites (like superuser.com or mathoverflow.com)
- Also, added [pnpm](https://pnpm.io) lock file (`pnpm-lock.yaml`) to `.gitignore`

anonoverflow: support other StackExchange sites

---

src/pages/options_src/App.svelte
src/pages/options_src/Sidebar.svelte
src/pages/popup_src/App.svelte

This PR is to fix some CJK display problems for Libredirect's Svelte UI:
- Sidebar: CJK texts are squashed and displayed vertically because they are wider than latin charaters. (Added `max-width: max-content` property for this)
- Options and popup pages do not have fallback fonts, which makes CJK texts appear in a serif font that doesn't quite match the default Inter font. (Added `sans-serif` as fallback)
- Fix the translation key for the Service menu.
|Before|After|
|---|---|
|![before this change](https://github.com/user-attachments/assets/d86d217d-193a-4e55-a642-38d59f312969)|![after this change](https://github.com/user-attachments/assets/9048bb75-ed82-43cf-ad94-d8512c8c0857)|

Fix: sidebar text layouts and font fallbacks for CJK

---

src/assets/javascripts/services.js
src/config.json

Closes #991. `subdomain[1]` will be `undefined` when there is nothing before `redd.it` in the string but since there's nothing else to test I just made it `default`. To be rigorous it can be changed to `case undefined` though

Redirect redd.it/xxxxxx shortlinks

---

src/assets/javascripts/services.js

The us.kg is a very controversial domain, we've had to make the hard decision to switch to a different provider.

[service: ytify] change domain

---

src/assets/javascripts/services.js
src/config.json

This PR addresses three issues:
1. Country code subdomains like ru.pinterest.com currently aren't redirected
2. pin.it shortlinks redirect to a 404. They expand to api.pinterest.com first so we have to whitelist that, and then to /pin/\<id\>/sent which is what causes the 404 on Painterest's side
3. Reversing the URL was not implemented

Pinterest: redirect subdomains, fix shortlinks, add reverse
