libredirect/browser_extension

src/manifest.json

Can't install crx on chrome otherwise

Replace all svg with png

---

src/assets/javascripts/helpers/youtube/youtube.js

Fixes ordering issue made by merging #168

Rearranged Order of Instances 

---

src/instances/piped-instances.json

This .json file is made for fetching of instances by the Python Script as Currently the Piped Instances are updated only when the Extension updates. So, This would solve the problem by updating the Script and utilizing this file.

Created Piped-instance.json

---

src/instances/piped.json

New Instance : https://piped.shimul.me/

Added Piped Instance

---

src/instances/piped.json

Just breaks urls, please don't do it :(

Removed trailing slash

---

chromium.md

For the love of Unix how has it been live for so long?

chromium.md: fix typo

---

README.md

This PR adds the newly added redirects libremdb and quetre to readme
#230

Add quetre and libremdb to readme

---

src/instances/get_instances.py

In this pull request I updated `rimgo` function in get_instances.py file so it's compatible with new format of instances.json file from Rimgo repository.
See this pull request for more details about format change: https://codeberg.org/video-prize-ranch/rimgo/pulls/39

Update rimgo function in get_instances.py

---

src/instances/get_instances.py

In this pull request I updated `wikiless` function in get_instances.py file so it's compatible with new format of instances.json file from Wikiless repository.
See this pull request for more details about format change: https://codeberg.org/orenom/Wikiless/pulls/71

Update wikiless function in get_instances.py

---

README.md

This is the official link of [send](https://gitlab.com/timvisee/send) . Github one is a [mirror](https://github.com/timvisee/send)

update link of "send"

---

src/instances/blacklist.json
src/instances/data.json
src/instances/piped.json

The Instance is added to cloudflare block list as it uses CF as CDN.
This PR will be a draft until this issue is closed - https://github.com/TeamPiped/Piped/issues/1168.

Added New Piped Instance - palash.dev

---

src/assets/javascripts/services.js

Please add `hacktoberfest-accepted` label to this PR
Another PR will be made for teddit, just that I need to wait for [this](https://codeberg.org/teddit/teddit/pulls/355)

Properly redirect images in Libreddit

---

src/pages/options/index.js

The function code was very difficult to read, so I decided to refactor it

Refactor createList function

---

src/pages/options/widgets/services.pug

Allow access to 'Show in popup' checkbox while the service is disabled

---

src/assets/javascripts/services.js
src/config.json

- For example:
- gist view is supported: [GitHub](https://gist.github.com/fguisso/1403912bd1b8ff53f4a7919f0bb9399a) | [GotHub](https://gothub.projectsegfau.lt/gist/fguisso/1403912bd1b8ff53f4a7919f0bb9399a)
- gist user isn't supported: [GitHub](https://gist.github.com/libredirect) | [GotHub](https://gothub.projectsegfau.lt/gist/libredirect)

Add GitHub gists support

---

src/assets/javascripts/localise.js
src/assets/javascripts/services.js
src/assets/javascripts/utils.js
src/pages/options/index.js

Add jsdoc types for some functions

---

src/assets/javascripts/services.js
src/assets/javascripts/utils.js
src/config.json

Note: I didn't add `Tekstowo.pl`'s icon,
Also currently there are no self-hosted instances.

Add TekstoLibre, frontend for Tekstowo.pl

---

src/assets/javascripts/services.js
src/assets/javascripts/utils.js

I usually have 1-2 instances, and attempting to switch between them and get the same instance 5+ times in a row is annoying, especially on mobile :)

switchInstance returns next instance instead of random

---

src/assets/javascripts/services.js

While working on #869 I noticed that a couple debug console.log statements were left in the code

Remove debug console.log statements

---

src/pages/popup/popup.pug

Re-order the popup menu items to improve UI / UX

---

src/assets/javascripts/services.js

Moves the rewrite functionality to its own separate function

Move rewrite logic to own function

---

src/assets/javascripts/services.js

As of [Intellectual v0.8.0](https://github.com/Insprill/intellectual/releases/tag/v0.8.0), all Intellectual paths match Genius paths, so no path rewrites are required.

Update Intellectual redirects

---

src/config.json

Additionally, the other instances are linked in the updated url

update tubo git repo

---

src/assets/javascripts/services.js
src/config.json

closes #944 
depends on https://github.com/libredirect/instances/pull/30

Add Materialious

---

src/_locales/ja/messages.json

Untranslated parts and improvements.

Update messages.json Japanese

---

src/_locales/delete.py
src/_locales/en/messages.json
src/_locales/filter.py

This PR is to:
- Sync the latest i18n strings to the English translation file, make them translatable on Weblate.

Update the i18n source strings

---

src/pages/options_src/Services/Instances.svelte

Just copied the Remove Instance button over, closes #990

Switch to remove button for selected instances

---

src/assets/javascripts/services.js
src/config.json

Just adding `(meta\.)?`, no need to filter out the dot or anything since we're not comparing it, just checking for its presence

redirect *.meta.stackexchange.com

---

src/assets/javascripts/services.js
src/config.json

Depends on https://github.com/libredirect/instances/pull/33

Add soundcloak
